services:
  producer:
    build: .
    environment:
      - REDIS_HOST=my-redis-stream
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    networks:
      - my-redis-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  my-redis-network:
    external: true