services:
  mc-producer:
    build: .
    networks:
      - confluent-kafka-rust_kafka_network
    
    deploy:
      replicas: 1
      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    environment:
      - PYTHONUNBUFFERED=1

networks:
  confluent-kafka-rust_kafka_network:
    external: true
